name: package
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    deb:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: jwlawson/actions-setup-cmake@v1.12
              name: Setup cmake
            - name: Run CMake
              run: |
                  mkdir build
                  cd build
                  cmake ..
                  make
            - name: Create folder structure
              run: |
                  mkdir -p .debpkg/usr/bin
                  cp build/sxhkd-cheatsheet .debpkg/usr/bin/sxhkd-cheatsheet
            - name: Read version code
              id: getversion
              run: echo "::set-output name=version::$(less CMakeLists.txt | grep -E "\s+VERSION\s" --color=never | sed 's/\s*VERSION\s*//')"
            - name: Generate build number
              id: buildnumber
              uses: einaregilsson/build-number@v3
              with:
                  token: ${{secrets.github_token}}
            - uses: jiro4989/build-deb-action@v2
              with:
                  package: sxhkd-cheatsheet
                  package_root: .debpkg
                  maintainer: Giacomo Zanolli
                  version: v${{ steps.getversion.outputs.version }} #+${{ steps.buildnumber.outputs.build_number }}
                  desc: >
                      Displays your sxhkd configuration in a simple and colorful
                      Text-based User Interface.
            - name: Archive deb package
              uses: actions/upload-artifact@v3
              with:
                  name: deb
                  path: |
                      sxhkd-cheatsheet_*.deb
    # rpm:
    #     runs-on: ubuntu-22.04
    #     steps:
    #         - uses: actions/checkout@v3
    # flatpak:
    #     runs-on: ubuntu-22.04
    #     steps:
    #         - uses: actions/checkout@v3
    # appimage:
    #     runs-on: ubuntu-22.04
    #     steps:
    #         - uses: actions/checkout@v3
    # snap:
    #     runs-on: ubuntu-22.04
    #     steps:
    #         - uses: actions/checkout@v3
